import React, { useState } from 'react';
import {
  Bot,
  CheckCircle2,
  Copy,
  Check,
  Clock,
  Coins,
  Brain,
  ChevronDown,
  ChevronRight,
  Loader2,
  FileText,
  Code,
  AlertTriangle,
  ShieldAlert,
  Sparkles,
} from 'lucide-react';
import type {
  NodeType,
  NodeStatus,
  NodeExecutionResult,
  SelfHealingTraceStep,
  StructuredOutputError,
} from '../../../engine/types.ts';
import { useTranslation } from '../../../i18n/useTranslation.ts';

function stripMarkdown(md: string): string {
  return md
    .replace(/```[\s\S]*?```/g, (m) => m.replace(/```[a-z]*\n?/gi, '').replace(/```/g, ''))
    .replace(/`([^`]+)`/g, '$1')
    .replace(/^#+\s+(.*)$/gm, '$1')
    .replace(/(\*\*|__)(.*?)\1/g, '$2')
    .replace(/(\*|_)(.*?)\1/g, '$2')
    .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1')
    .replace(/^\s*[-*+]\s+/gm, '')
    .replace(/^\s*\d+\.\s+/gm, '')
    .trim();
}

function formatPortfolioLog(
  trace: SelfHealingTraceStep[],
  isValidationFailed: boolean,
  fallbackReason: string | undefined,
  totalAttempts: number,
  outputData: Record<string, unknown>,
): string {
  const statusStr = isValidationFailed
    ? '⚠️ 优雅降级兜底 (_validationFailed: true，未向外抛错)'
    : totalAttempts > 1
      ? `✅ 自愈成功 (经历 ${totalAttempts} 轮调用，${totalAttempts - 1} 次自动纠偏)`
      : '✅ 一次性校验通过 (0 次重试)';

  let md = `### 🛡️ AI 工作流确定性结构化输出与自愈状态机复盘日志\n\n`;
  md += `- **执行结果**: ${statusStr}\n`;
  md += `- **总调用轮次**: ${totalAttempts} 轮 (最大自愈预算: 2 次重试 / 3 次总调用)\n`;
  md += `- **双层防御网**: L1 格式约束 (json_schema / json_object) + L2 业务契约深度校验 (Zod safeParse)\n`;
  if (fallbackReason) {
    md += `- **降级分支特异性**: \`${fallbackReason}\`\n`;
  }
  md += `\n---\n\n#### 📜 轮次执行明细 (Execution Trace Timeline)\n\n`;

  trace.forEach((step) => {
    const roundTitle =
      step.round === 1
        ? `Round 1 (初次生成 / Initial Generation)`
        : `Round ${step.round} (第 ${step.round - 1} 次自愈重试 / Self-Healing Retry #${step.round - 1})`;

    md += `##### 🔹 ${roundTitle}\n`;
    md += `- **Finish Reason**: \`${step.finishReason || 'stop'}\`\n`;
    md += `- **L1 语法层**: ${step.syntaxValid ? '✅ 语法解析合法 (Syntax Valid)' : '❌ 语法异常 (Syntax Invalid)'}\n`;
    md += `- **L2 业务契约层**: ${
      step.semanticValid
        ? '✅ 全部通过 (Semantic Valid)'
        : `❌ 规则拦截 (Caught by L2 Semantic Defense, ${step.errors?.length || 0} 处违规)`
    }\n`;

    if (step.escalationLevel) {
      const levelMap: Record<string, string> = {
        surgical_prescription: '🎯 字段级靶向手术刀处方 (Triad Diagnostic)',
        golden_exemplar: '🌟 全量 Schema 契约 + Few-Shot 黄金示例灌顶 (Global Grounding)',
        clean_empty_retry: '🔄 原地干净重试 (Zero-Pollution Empty Retry)',
        truncation_compression: '✂️ 截断特异性紧凑压缩自愈 (Adaptive Truncation Compaction)',
      };
      md += `- **自愈阶梯策略**: ${levelMap[step.escalationLevel] || step.escalationLevel}\n`;
    }

    if (step.healedFromTruncation) {
      md += `- **特异性成效**: 🎉 成功从 Token 长度截断中自动压缩自愈！\n`;
    }

    if (step.errors && step.errors.length > 0) {
      md += `- **契约拦截明细 (Field Diagnostics - 违规值/约束/处方三要素)**:\n`;
      step.errors.forEach((err) => {
        md += `  - \`[${err.path}]\`: ${err.message}\n`;
        if (err.receivedValue !== undefined) {
          md += `    * 实际输出值: \`${typeof err.receivedValue === 'string' ? err.receivedValue : JSON.stringify(err.receivedValue)}\`\n`;
        }
        if (err.expectedRule) {
          md += `    * 约束规则: ${err.expectedRule}\n`;
        }
        if (err.suggestion) {
          md += `    * 修复处方: ${err.suggestion}\n`;
        }
      });
    }

    if (step.rawOutput !== undefined) {
      md += `- **本轮原始输出**:\n\`\`\`json\n${step.rawOutput || '(空输出 / Empty)'}\n\`\`\`\n`;
    }

    if (step.feedbackPrompt) {
      const quoted = step.feedbackPrompt
        .split('\n')
        .map((line) => `> ${line}`)
        .join('\n');
      md += `- **注入自愈记忆 (Injected Diagnostic Memory)**:\n${quoted}\n`;
    }

    md += `\n`;
  });

  if (!isValidationFailed && outputData['parsed']) {
    md += `---\n\n#### 🎯 最终收敛结构化数据 (Final Validated Contract Output)\n\`\`\`json\n${JSON.stringify(
      outputData['parsed'],
      null,
      2,
    )}\n\`\`\`\n`;
  }

  md += `\n---\n*Generated by PatchCat Deterministic DAG Engine · AI Workflow Orchestration*\n`;
  return md;
}

interface ExecutionResultViewerProps {
  type: NodeType;
  status?: NodeStatus;
  outputs: Record<string, unknown>;
  executionResult?: NodeExecutionResult;
  error?: string;
}

export const ExecutionResultViewer: React.FC<ExecutionResultViewerProps> = ({
  type,
  status,
  outputs,
  executionResult,
  error,
}) => {
  const { t, language } = useTranslation();
  const [copiedFormat, setCopiedFormat] = useState<'md' | 'text' | 'json' | null>(null);
  const [copiedError, setCopiedError] = useState(false);
  const [showReasoning, setShowReasoning] = useState(true);

  const trace = (Array.isArray(outputs['selfHealingTrace'])
    ? outputs['selfHealingTrace']
    : []) as SelfHealingTraceStep[];
  const isValidationFailed = Boolean(outputs['_validationFailed']);
  const fallbackReason = outputs['fallbackReason'] as string | undefined;
  const validationErrors = (Array.isArray(outputs['errors'])
    ? outputs['errors']
    : []) as StructuredOutputError[];
  const attempts =
    typeof outputs['selfHealingAttempts'] === 'number'
      ? (outputs['selfHealingAttempts'] as number)
      : trace.length;

  const [showSelfHealingTrace, setShowSelfHealingTrace] = useState(true);
  const [copiedPortfolioLog, setCopiedPortfolioLog] = useState(false);

  const handleCopyPortfolioLog = () => {
    if (trace.length === 0) return;
    const md = formatPortfolioLog(
      trace,
      isValidationFailed,
      fallbackReason,
      attempts || trace.length,
      outputs,
    );
    navigator.clipboard.writeText(md).then(() => {
      setCopiedPortfolioLog(true);
      setTimeout(() => setCopiedPortfolioLog(false), 2000);
    });
  };

  const handleCopyFormat = (format: 'md' | 'text' | 'json', formattedStr: string) => {
    let content = '';
    if (format === 'json') {
      content = JSON.stringify(outputs, null, 2);
    } else if (format === 'md') {
      content = formattedStr;
    } else {
      content = stripMarkdown(formattedStr);
    }
    if (!content) return;
    navigator.clipboard.writeText(content).then(() => {
      setCopiedFormat(format);
      setTimeout(() => setCopiedFormat(null), 2000);
    });
  };

  const getFormattedOutput = (outputData: Record<string, unknown>): string => {
    if (typeof outputData['response'] === 'string') {
      return outputData['response'];
    }
    if (typeof outputData['output'] === 'string') {
      return outputData['output'];
    }
    if (typeof outputData['output'] === 'object' && outputData['output'] !== null) {
      return JSON.stringify(outputData['output'], null, 2);
    }
    if (typeof outputData['result'] === 'string') {
      return outputData['result'];
    }
    if (typeof outputData['result'] === 'object' && outputData['result'] !== null) {
      return JSON.stringify(outputData['result'], null, 2);
    }
    if (typeof outputData['promptText'] === 'string') {
      return outputData['promptText'];
    }
    if (typeof outputData['context'] === 'string') {
      return outputData['context'];
    }
    if (Object.keys(outputData).length > 0) {
      return JSON.stringify(outputData, null, 2);
    }
    return '';
  };

  const effectiveError =
    error ||
    executionResult?.error ||
    (typeof outputs['error'] === 'string' ? outputs['error'] : undefined);
  const isError = status === 'error' || Boolean(effectiveError);

  const outputString = getFormattedOutput(outputs);
  const hasOutputs = Object.keys(outputs).length > 0 && outputString.length > 0;

  return (
    <div className="space-y-3 pt-2 border-t border-slate-200 dark:border-slate-800/80">
      <div className="flex items-center justify-between">
        <label className="text-[11px] font-semibold text-slate-500 dark:text-slate-400 uppercase tracking-wider flex items-center gap-1.5">
          {isError ? (
            <AlertTriangle className="w-3.5 h-3.5 text-rose-500" />
          ) : isValidationFailed ? (
            <ShieldAlert className="w-3.5 h-3.5 text-amber-500" />
          ) : type === 'llm' || type === 'agent' ? (
            <Bot className="w-3.5 h-3.5 text-blue-600 dark:text-sky-400" />
          ) : (
            <CheckCircle2 className="w-3.5 h-3.5 text-emerald-600 dark:text-emerald-400" />
          )}
          <span
            className={
              isError
                ? 'text-rose-600 dark:text-rose-400 font-bold'
                : isValidationFailed
                  ? 'text-amber-600 dark:text-amber-400 font-bold'
                  : ''
            }
          >
            {isError
              ? language === 'zh'
                ? '执行异常与输出结果'
                : 'Execution Error & Results'
              : isValidationFailed
                ? language === 'zh'
                  ? '确定性降级输出与自愈轨迹'
                  : 'Deterministic Fallback & Trace'
                : t.propertyPanel.finalOutput}
          </span>
        </label>
        {hasOutputs && (
          <div className="flex items-center gap-1">
            <button
              onClick={() => handleCopyFormat('md', outputString)}
              className="flex items-center gap-1 text-[10px] text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white px-2 py-0.5 rounded bg-slate-100 dark:bg-slate-800 hover:bg-slate-200 dark:hover:bg-slate-700 transition-colors shadow-xs cursor-pointer"
              title={t.ergonomics.copyMarkdown}
            >
              {copiedFormat === 'md' ? (
                <Check className="w-3 h-3 text-emerald-600 dark:text-emerald-400" />
              ) : (
                <FileText className="w-3 h-3" />
              )}
              <span>MD</span>
            </button>
            <button
              onClick={() => handleCopyFormat('text', outputString)}
              className="flex items-center gap-1 text-[10px] text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white px-2 py-0.5 rounded bg-slate-100 dark:bg-slate-800 hover:bg-slate-200 dark:hover:bg-slate-700 transition-colors shadow-xs cursor-pointer"
              title={t.ergonomics.copyPlainText}
            >
              {copiedFormat === 'text' ? (
                <Check className="w-3 h-3 text-emerald-600 dark:text-emerald-400" />
              ) : (
                <Copy className="w-3 h-3" />
              )}
              <span>TXT</span>
            </button>
            <button
              onClick={() => handleCopyFormat('json', outputString)}
              className="flex items-center gap-1 text-[10px] text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white px-2 py-0.5 rounded bg-slate-100 dark:bg-slate-800 hover:bg-slate-200 dark:hover:bg-slate-700 transition-colors shadow-xs cursor-pointer"
              title={t.ergonomics.copyRawJson}
            >
              {copiedFormat === 'json' ? (
                <Check className="w-3 h-3 text-emerald-600 dark:text-emerald-400" />
              ) : (
                <Code className="w-3 h-3" />
              )}
              <span>JSON</span>
            </button>
          </div>
        )}
      </div>

      {/* Telemetry metadata badges */}
      {executionResult && (
        <div className="flex items-center gap-2 text-[10px] font-mono">
          {executionResult.latencyMs !== undefined && (
            <span
              className={`flex items-center gap-1 px-2 py-0.5 rounded border ${
                isError
                  ? 'bg-rose-50 dark:bg-rose-500/10 border-rose-200 dark:border-rose-500/20 text-rose-700 dark:text-rose-300'
                  : 'bg-blue-50 dark:bg-sky-500/10 border-blue-200 dark:border-sky-500/20 text-blue-700 dark:text-sky-300'
              }`}
            >
              <Clock className="w-3 h-3" />
              <span>{executionResult.latencyMs}ms</span>
            </span>
          )}
          {executionResult.tokenUsage && (
            <span className="flex items-center gap-1 px-2 py-0.5 rounded bg-amber-50 dark:bg-amber-500/10 border border-amber-200 dark:border-amber-500/20 text-amber-700 dark:text-amber-300">
              <Coins className="w-3 h-3" />
              <span>{executionResult.tokenUsage.total} tokens</span>
            </span>
          )}
        </div>
      )}

      {/* Formatted Output Viewer Box */}
      <div className="space-y-2.5">
        {/* Graceful Degradation Banner (When _validationFailed === true, NEVER THROW) */}
        {isValidationFailed && (
          <div className="rounded-xl bg-amber-50/90 dark:bg-amber-950/30 border border-amber-300 dark:border-amber-800/60 p-3.5 space-y-2.5 shadow-xs">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-1.5 text-xs font-bold text-amber-800 dark:text-amber-300">
                <ShieldAlert className="w-4 h-4 text-amber-600 dark:text-amber-400 shrink-0" />
                <span>
                  {language === 'zh'
                    ? '确定性优雅降级已激活 (Never Throw)'
                    : 'Graceful Degradation Active (Never Throw)'}
                </span>
              </div>
              <span className="text-[10px] font-mono px-2 py-0.5 rounded-full bg-amber-100 dark:bg-amber-900/50 text-amber-700 dark:text-amber-300 border border-amber-300 dark:border-amber-700/50 font-semibold">
                _validationFailed: true
              </span>
            </div>

            <div className="text-[11px] text-amber-900 dark:text-amber-200/90 leading-relaxed">
              {language === 'zh' ? (
                <>
                  业务契约校验未收敛，引擎已按照架构规约<strong>避免抛出异常崩溃</strong>，输出标准化降级标记。下游 Condition 节点可直接依据{' '}
                  <code className="px-1 py-0.5 rounded bg-amber-100 dark:bg-amber-900/60 text-amber-800 dark:text-amber-300 font-mono text-[10px]">
                    _validationFailed
                  </code>{' '}
                  路由至兜底人工或降级策略分支。
                </>
              ) : (
                <>
                  Validation constraints were not satisfied. Following deterministic architecture, the engine{' '}
                  <strong>did not throw</strong>. Downstream condition nodes can safely route using{' '}
                  <code className="px-1 py-0.5 rounded bg-amber-100 dark:bg-amber-900/60 text-amber-800 dark:text-amber-300 font-mono text-[10px]">
                    _validationFailed
                  </code>
                  .
                </>
              )}
            </div>

            <div className="flex flex-wrap items-center gap-1.5 pt-0.5 text-[10px] font-mono">
              {fallbackReason && (
                <span className="px-2 py-0.5 rounded bg-white/70 dark:bg-black/30 border border-amber-200 dark:border-amber-800/40 text-amber-800 dark:text-amber-300">
                  {language === 'zh' ? '分支特异性' : 'Fallback Reason'}: {fallbackReason}
                </span>
              )}
              {validationErrors.length > 0 && (
                <span className="px-2 py-0.5 rounded bg-rose-50 dark:bg-rose-950/40 border border-rose-200 dark:border-rose-900/40 text-rose-700 dark:text-rose-300">
                  {language === 'zh' ? '未收敛违规项' : 'Violations'}: {validationErrors.length}
                </span>
              )}
            </div>

            {validationErrors.length > 0 && (
              <div className="p-2.5 rounded-lg bg-white/80 dark:bg-black/40 border border-amber-200/60 dark:border-amber-900/30 space-y-1">
                <div className="text-[10px] font-bold text-amber-800 dark:text-amber-400 uppercase tracking-wider">
                  {language === 'zh' ? 'L2 领域规则拦截诊断' : 'L2 Semantic Defense Diagnostics'}:
                </div>
                {validationErrors.map((err, i) => (
                  <div
                    key={i}
                    className="text-[11px] font-mono flex items-start gap-1 text-slate-700 dark:text-slate-300"
                  >
                    <span className="font-semibold text-rose-600 dark:text-rose-400 shrink-0">
                      [{err.path}]:
                    </span>
                    <span className="text-slate-600 dark:text-slate-300">{err.message}</span>
                  </div>
                ))}
              </div>
            )}
          </div>
        )}

        {/* Deterministic Self-Healing Trace Timeline Card */}
        {trace.length > 0 && (
          <div className="rounded-xl bg-slate-50/90 dark:bg-slate-900/60 border border-slate-200 dark:border-slate-800 p-3.5 space-y-3 shadow-xs">
            <div className="flex items-center justify-between">
              <button
                type="button"
                onClick={() => setShowSelfHealingTrace(!showSelfHealingTrace)}
                className="flex items-center gap-1.5 text-xs font-bold text-slate-800 dark:text-slate-200 hover:text-blue-600 dark:hover:text-sky-400 transition-colors cursor-pointer"
              >
                <Sparkles className="w-4 h-4 text-sky-500 shrink-0" />
                <span>
                  {language === 'zh'
                    ? '确定性自愈状态机执行轨迹'
                    : 'Self-Healing State Machine Trace'}
                </span>
                {showSelfHealingTrace ? (
                  <ChevronDown className="w-3.5 h-3.5 text-slate-400" />
                ) : (
                  <ChevronRight className="w-3.5 h-3.5 text-slate-400" />
                )}
              </button>

              <div className="flex items-center gap-1.5">
                <span
                  className={`text-[10px] font-mono px-2 py-0.5 rounded-full font-semibold border ${
                    isValidationFailed
                      ? 'bg-amber-50 dark:bg-amber-950/40 text-amber-700 dark:text-amber-400 border-amber-300 dark:border-amber-700'
                      : trace.length > 1
                        ? 'bg-emerald-50 dark:bg-emerald-950/40 text-emerald-700 dark:text-emerald-400 border-emerald-300 dark:border-emerald-700'
                        : 'bg-sky-50 dark:bg-sky-950/40 text-sky-700 dark:text-sky-400 border-sky-300 dark:border-sky-700'
                  }`}
                >
                  {isValidationFailed
                    ? language === 'zh'
                      ? '优雅降级兜底'
                      : 'Degraded'
                    : trace.length > 1
                      ? language === 'zh'
                        ? `第 ${trace.length} 轮自愈成功 (${trace.length - 1}次重试)`
                        : `Healed in Round ${trace.length}`
                      : language === 'zh'
                        ? '一次性通过 (0重试)'
                        : 'Direct Pass (0 Retries)'}
                </span>

                <button
                  type="button"
                  onClick={handleCopyPortfolioLog}
                  className="flex items-center gap-1 text-[10px] font-medium text-sky-700 dark:text-sky-300 hover:text-sky-900 dark:hover:text-white px-2 py-0.5 rounded bg-sky-100/80 dark:bg-sky-900/40 hover:bg-sky-200 dark:hover:bg-sky-900/60 border border-sky-200 dark:border-sky-800 transition-all cursor-pointer shadow-xs"
                  title={
                    language === 'zh'
                      ? '一键复制格式完整的 Markdown 复盘日志，适合放入作品集或技术博客'
                      : 'Copy full Markdown portfolio log'
                  }
                >
                  {copiedPortfolioLog ? (
                    <Check className="w-3 h-3 text-emerald-600 dark:text-emerald-400" />
                  ) : (
                    <Copy className="w-3 h-3" />
                  )}
                  <span>
                    {copiedPortfolioLog
                      ? language === 'zh'
                        ? '已复制'
                        : 'Copied'
                      : language === 'zh'
                        ? '复制作品集日志'
                        : 'Copy Portfolio Log'}
                  </span>
                </button>
              </div>
            </div>

            {showSelfHealingTrace && (
              <div className="space-y-2.5 pt-1">
                {trace.map((step, idx) => (
                  <div
                    key={idx}
                    className="p-2.5 rounded-lg bg-white dark:bg-slate-950 border border-slate-200/80 dark:border-slate-800/80 text-xs space-y-1.5"
                  >
                    <div className="flex items-center justify-between text-[11px]">
                      <div className="flex items-center gap-1.5 font-bold text-slate-800 dark:text-slate-200 font-mono">
                        <span className="w-4 h-4 rounded-full bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-300 flex items-center justify-center text-[10px]">
                          {step.round}
                        </span>
                        <span>
                          {step.round === 1
                            ? language === 'zh'
                              ? 'Round 1 (初次生成)'
                              : 'Round 1 (Initial)'
                            : language === 'zh'
                              ? `Round ${step.round} (自愈重试 #${step.round - 1})`
                              : `Round ${step.round} (Retry #${step.round - 1})`}
                        </span>
                      </div>
                      <div className="flex items-center gap-1 text-[10px] font-mono">
                        <span
                          className={`px-1.5 py-0.5 rounded border ${
                            step.syntaxValid
                              ? 'bg-emerald-50 dark:bg-emerald-950/30 text-emerald-600 dark:text-emerald-400 border-emerald-200 dark:border-emerald-800'
                              : 'bg-rose-50 dark:bg-rose-950/30 text-rose-600 dark:text-rose-400 border-rose-200 dark:border-rose-800'
                          }`}
                        >
                          {step.syntaxValid ? 'L1 语法通过' : 'L1 语法错误'}
                        </span>
                        <span
                          className={`px-1.5 py-0.5 rounded border ${
                            step.semanticValid
                              ? 'bg-emerald-50 dark:bg-emerald-950/30 text-emerald-600 dark:text-emerald-400 border-emerald-200 dark:border-emerald-800'
                              : 'bg-rose-50 dark:bg-rose-950/30 text-rose-600 dark:text-rose-400 border-rose-200 dark:border-rose-800'
                          }`}
                        >
                          {step.semanticValid ? 'L2 契约通过' : 'L2 契约拦截'}
                        </span>
                        {step.escalationLevel && (
                          <span className="px-1.5 py-0.5 rounded bg-amber-50 dark:bg-amber-950/40 text-amber-700 dark:text-amber-300 border border-amber-200 dark:border-amber-800/50 font-mono text-[9px]">
                            {step.escalationLevel === 'surgical_prescription'
                              ? '🎯 手术刀处方'
                              : step.escalationLevel === 'golden_exemplar'
                                ? '🌟 黄金示例灌顶'
                                : step.escalationLevel === 'truncation_compression'
                                  ? '✂️ 截断压缩自愈'
                                  : '🔄 干净重试'}
                          </span>
                        )}
                        {step.healedFromTruncation && (
                          <span className="px-1.5 py-0.5 rounded bg-emerald-100 dark:bg-emerald-950/50 text-emerald-700 dark:text-emerald-300 border border-emerald-300 font-bold text-[9px]">
                            🎉 截断自愈成功
                          </span>
                        )}
                        {step.finishReason && (
                          <span className="px-1.5 py-0.5 rounded bg-slate-100 dark:bg-slate-800 text-slate-500 font-mono">
                            {step.finishReason}
                          </span>
                        )}
                      </div>
                    </div>

                    {step.errors && step.errors.length > 0 && (
                      <div className="p-2 rounded bg-rose-50/60 dark:bg-rose-950/30 border border-rose-100 dark:border-rose-900/30 space-y-1">
                        {step.errors.map((e, errIdx) => (
                          <div
                            key={errIdx}
                            className="text-[10px] font-mono text-rose-700 dark:text-rose-300 space-y-0.5"
                          >
                            <div className="flex items-start gap-1 font-semibold">
                              <span className="shrink-0">[{e.path}]:</span>
                              <span>{e.message}</span>
                            </div>
                            {(e.receivedValue !== undefined || e.expectedRule || e.suggestion) && (
                              <div className="pl-3 text-[9px] text-slate-600 dark:text-slate-400 space-y-0.5 border-l border-rose-200 dark:border-rose-800/60">
                                {e.receivedValue !== undefined && (
                                  <div>
                                    <span className="text-slate-400">输出值: </span>
                                    <span className="font-semibold text-rose-600 dark:text-rose-400">
                                      {typeof e.receivedValue === 'string'
                                        ? e.receivedValue
                                        : JSON.stringify(e.receivedValue)}
                                    </span>
                                  </div>
                                )}
                                {e.expectedRule && (
                                  <div>
                                    <span className="text-slate-400">约束: </span>
                                    <span>{e.expectedRule}</span>
                                  </div>
                                )}
                                {e.suggestion && (
                                  <div>
                                    <span className="text-emerald-600 dark:text-emerald-400 font-semibold">处方: </span>
                                    <span className="text-emerald-700 dark:text-emerald-300">{e.suggestion}</span>
                                  </div>
                                )}
                              </div>
                            )}
                          </div>
                        ))}
                      </div>
                    )}

                    {step.feedbackPrompt && (
                      <div className="p-2 rounded bg-indigo-50/50 dark:bg-indigo-950/20 border border-indigo-100 dark:border-indigo-900/30 space-y-0.5 text-[10px]">
                        <span className="font-semibold text-indigo-700 dark:text-indigo-300 block font-mono">
                          💡 注入纠错记忆 (Injected Diagnostic):
                        </span>
                        <div className="font-mono text-slate-600 dark:text-slate-400 whitespace-pre-wrap leading-tight line-clamp-3 hover:line-clamp-none transition-all">
                          {step.feedbackPrompt}
                        </div>
                      </div>
                    )}

                    {step.rawOutput && (
                      <div className="p-2 rounded bg-slate-50 dark:bg-black/30 border border-slate-200/50 dark:border-slate-800/50 font-mono text-[10px] text-slate-600 dark:text-slate-400 max-h-24 overflow-y-auto whitespace-pre-wrap">
                        {step.rawOutput}
                      </div>
                    )}
                  </div>
                ))}
              </div>
            )}
          </div>
        )}

        {/* Error Detail Banner (Shown whenever an error occurred) */}
        {effectiveError && (
          <div className="rounded-xl bg-rose-50/80 dark:bg-rose-950/30 border border-rose-200 dark:border-rose-900/50 p-3.5 space-y-2 shadow-xs">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-1.5 text-xs font-bold text-rose-700 dark:text-rose-400">
                <AlertTriangle className="w-4 h-4 shrink-0" />
                <span>{language === 'zh' ? '运行异常报错信息' : 'Node Execution Error'}</span>
              </div>
              <button
                type="button"
                onClick={() => {
                  navigator.clipboard.writeText(effectiveError);
                  setCopiedError(true);
                  setTimeout(() => setCopiedError(false), 2000);
                }}
                className="flex items-center gap-1 text-[10px] text-rose-600 dark:text-rose-400 hover:text-rose-800 dark:hover:text-rose-300 px-2 py-0.5 rounded bg-rose-100/70 dark:bg-rose-900/40 hover:bg-rose-200 dark:hover:bg-rose-900/60 transition-colors cursor-pointer"
                title={language === 'zh' ? '复制完整报错信息' : 'Copy Full Error'}
              >
                {copiedError ? (
                  <Check className="w-3 h-3 text-emerald-600" />
                ) : (
                  <Copy className="w-3 h-3" />
                )}
                <span>
                  {copiedError
                    ? language === 'zh'
                      ? '已复制'
                      : 'Copied'
                    : language === 'zh'
                      ? '复制报错'
                      : 'Copy Error'}
                </span>
              </button>
            </div>
            <div className="p-2.5 rounded-lg bg-white/80 dark:bg-black/40 border border-rose-100 dark:border-rose-900/30 font-mono text-[11px] text-rose-700 dark:text-rose-300 max-h-48 overflow-y-auto whitespace-pre-wrap break-all leading-relaxed">
              {effectiveError}
            </div>
          </div>
        )}

        {/* Collapsible Reasoning Block (DeepSeek R1 / Thinking models) */}
        {typeof outputs['reasoning'] === 'string' && outputs['reasoning'].length > 0 && (
          <div className="rounded-xl bg-violet-50/70 dark:bg-purple-950/20 border border-violet-200 dark:border-purple-500/30 overflow-hidden shadow-xs">
            <button
              onClick={() => setShowReasoning(!showReasoning)}
              className="w-full px-3 py-2 flex items-center justify-between text-xs font-semibold text-violet-700 dark:text-purple-300 hover:bg-violet-100/50 dark:hover:bg-purple-900/30 transition-colors cursor-pointer"
            >
              <div className="flex items-center gap-1.5">
                <Brain className="w-3.5 h-3.5 text-violet-600 dark:text-purple-400" />
                <span>{t.propertyPanel.reasoningThought}</span>
              </div>
              {showReasoning ? (
                <ChevronDown className="w-3.5 h-3.5" />
              ) : (
                <ChevronRight className="w-3.5 h-3.5" />
              )}
            </button>
            {showReasoning && (
              <div className="p-3 text-[11px] font-mono text-violet-900 dark:text-purple-200/90 whitespace-pre-wrap leading-relaxed border-t border-violet-200/60 dark:border-purple-500/20 max-h-48 overflow-y-auto bg-white/40 dark:bg-black/20">
                {outputs['reasoning']}
                {status === 'running' && (
                  <span className="animate-pulse font-bold text-violet-600 dark:text-purple-400">
                    {' '}
                    ▌
                  </span>
                )}
              </div>
            )}
          </div>
        )}

        {/* Standard Response Content Box (Shown if outputs exist, or currently running, or idle without errors) */}
        {(hasOutputs || status === 'running' || !effectiveError) && (
          <div className="space-y-1.5">
            {effectiveError && hasOutputs && (
              <div className="text-[10px] font-mono font-semibold text-slate-500 dark:text-slate-400 uppercase tracking-wider">
                {language === 'zh' ? '异常前局部返回输出' : 'Partial Return Outputs'}
              </div>
            )}
            <div className="p-3.5 rounded-xl bg-slate-50 dark:bg-slate-950 border border-slate-200 dark:border-slate-800 font-mono text-xs text-slate-800 dark:text-slate-200 max-h-72 overflow-y-auto whitespace-pre-wrap leading-relaxed shadow-xs">
              {hasOutputs ? (
                <>
                  {outputString}
                  {status === 'running' && (
                    <span className="animate-pulse font-bold text-blue-500"> ▌</span>
                  )}
                </>
              ) : status === 'running' ? (
                <div className="flex items-center justify-center gap-2 py-4 text-blue-600 dark:text-sky-400">
                  <Loader2 className="w-4 h-4 animate-spin" />
                  <span>{t.propertyPanel.liveStreaming}...</span>
                </div>
              ) : (
                <span className="text-slate-400 dark:text-slate-500 italic text-center block py-2">
                  {t.propertyPanel.noNodeSelectedDesc}
                </span>
              )}
            </div>
          </div>
        )}
      </div>
    </div>
  );
};
